services:
  eureka-server:
    image: "mayurjagtap/eureka-service-discovery:v1"
    container_name: "eureka-ms"
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomm
  configservice:
    image: "mayurjagtap/config-service:v1"
    container_name: config-ms
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomm
  postgres:
    image: "postgres:16"
    container_name: "postgres-db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    networks:
      - ecomm
  order:
    image: "mayurjagtap/order-service:v1"
    container_name: order-ms
    depends_on:
      - configservice
      - postgres
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_NAME: "order"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/mars"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8888/"
      SPRING_PROFILES_ACTIVE: "prod"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomm
  inventory:
    image: "mayurjagtap/inventory-service:v1"
    container_name: inventory-ms
    depends_on:
      - configservice
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_NAME: "inventory"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8888/"
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomm
networks:
  ecomm:
    driver: bridge
volumes:
  postgres_data:
