spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  profiles:
    active: dev
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gatewayserver"
    description: "Gateway server of Ecomm Application"
    version: "V1.0"

logging:
  level:
    org:
      shopping_kart: DEBUG

