server:
  port: 8088
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/mars
    username: ${DB_USER:postgres}
    password: ${DB_SECRET:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8888/"
#spring.jpa.properties.hibernate.jdbc.time_zone= Asia/Kolkata

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      access: UNRESTRICTED
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "orderservice"
    description: "Ecomm App Order Service"
    version: "1.0.0"
