server:
  port: 8088
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/mars
    username: ${DB_USER:postgres}
    password: ${DB_SECRET:mayur}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  #profiles:
   # active: "prod"
  config:
    import: "optional:configserver:http://localhost:8888/"
#spring.jpa.properties.hibernate.jdbc.time_zone= Asia/Kolkata

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  app:
    name: "orderservice"
    description: "This is the order service of Ecomm Application"
    Version: "V1.0"
