server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    #active: "native"
    active: "git"
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//mayurjagtap//Developer//project-workspace//ecomm-backend//config-repo"
        git:
          uri: "https://github.com/mayurjagtap786/ecomm-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
encrypt:
  key: "a572c0514135c84b2961d00c2012ab2f"
